### ISSUE TITLE
in_volume treats volumes as convex hulls

### ISSUE THREAD

**Issue by jefferis** [schlegelp/PyMaid#10]
> Uses scipy to test if points are within a given CATMAID volume. The idea is to test if adding the point to the cloud would change the convex hull. 
    
Doesn't this implicitly assume that the volume is a convey hull? Think about the convex hull of the mushroom body which looks a bit like a pyramid. It seems to me that a point could be inside the pyramid but far outside the alpha shape defining the mushroom body and still pass this test.

**Comment by schlegelp** [comment]
Good point! Will see if I can use `scipy.spatial.Delaunay` instead.

**Comment by schlegelp** [comment]
Found a Python-only library that uses Octrees to intersect rays with volumes: `pyoctree` (https://github.com/mhogg/pyoctree)

For example see [here](https://github.com/mhogg/pyoctree/blob/master/pyoctree/Examples/pyoctree-intro.ipynb)

Initial tests look promising. Will run some more to check performance before implementing.

**Comment by schlegelp** [comment]
Implemented with commit ba4b2663e4374054d3c8ec7b00c2a40105cf7a0a
