### ISSUE TITLE
add algorithms from Schneider-Mizell et al.

### ISSUE THREAD

**Issue by schlegelp** [schlegelp/PyMaid#15]
E.g. flow centrality, axon-dendrite split, etc.

**Comment by jefferis** [comment]
Has Casey done some of this in python already? Incidentally Alex has implemented this in R here: https://github.com/alexanderbates/catnat/blob/master/R/flowcentrality.R. I do wish there were a way to avoid re-writing all this stuff multiple times.

**Comment by schlegelp** [comment]
I don't think so. He used Matlab for the analysis and I can't find anything written in Python on his [repository] (https://github.com/ceesem/catpy). Will write him to see if he has anything handy that he'd be willing to contribute. This is not a priority anyway - I'm using the bug tracker mostly to keep track of ideas.

**Comment by schlegelp** [comment]
implemented with 7fec61001cfa0ec189957db380496351a54fdcbc
