### ISSUE TITLE
swc spec link re-directed

### ISSUE THREAD

**Issue by zhihaozheng** [schlegelp/pyMaid#182]
https://github.com/schlegelp/pyMaid/blob/64e3c8f9fe32065c24ffb834d44f744e848f2f9c/pymaid/utils.py#L631

The swc format spec link (http://research.mssm.edu/cnic/swc.html) is broken, same in the to_swc function.

**Comment by schlegelp** [comment]
Thanks! Fixed with 725572820564bebcbd9620887bb19d66c237d219
@jefferis: I believe nat is using the same link [here](https://jefferis.github.io/nat/reference/read.neuron.swc.html)
