### ISSUE TITLE
Improving the behavior of upload_neuron when using import_connectors=True

### ISSUE THREAD

**Issue by jasper-tms** [schlegelp/pymaid#196]
I'm writing some pymaid wrappers that pull neurons from a tracing project, transform them using an elastic 3D deformation (in my case, using elastix to warp the neurons from the EM dataset's coordinate system to the VNC atlas' coordinate system), and then upload those transformed neurons into a target catmaid project (which in my case contains the image stack of the VNC atlas). There are a few bug fixes/feature additions that I'm thinking of implementing within pymaid functions in order to enable this to work as desired. Namely, upload_neuron's import_connectors option works well when importing a new neuron with new synapses that don't need to be connected to any other neurons, but has undesired behavior in more complicated situations. I believe there is a straightforward fix for the following two situations, which are situations I'm encountering. I'm happy to implement these fixes, just wanted to run the ideas by you in case you have a different idea about how to solve the problems:

1. When transferring neurons between projects (either using the transfer_neuron function or by manually pulling the neurons, manipulating them somehow, and then using upload_neuron), if neuron A and neuron B are connected in a source project, and they're upload_neuron'ed into a target project with import_connectors=True, then anywhere there was a connector between neurons A and B in the source project, the target project will get two separate connectors uploaded on top of one another at the location of the original connector, with one connector linked to neuron A, and one connected to neuron B. As far as catmaid sees it, neuron A and B would then not be connected in the target project.
Proposed fix: in pymaid.add_connector, add some logic for a new function argument named 'check_existing' or something that causes add_connector to first check if a connector already exists in the target project at the desired location, and if so, to return that existing connector's information instead of creating a new connector at that location and returning the new connector's information. This way, when neuron B is uploaded, upload_neuron's calls to add_connector for neuron B would find the connectors already created during the neuron A upload, and so neuron B would get properly connected to neuron A. I suspect this check_existing option would be useful default behavior for many calls to it from other pymaid functions. (Perhaps a raise_already_existing option would also be useful, so calls can specify whether finding an already existing connector should be treated as an error or should just return that connector's information.) This check_existing option could be implemented using pymaid.get_connectors_in_bbox to check for connectors at a given location. I just asked Tom to [fix a bug in the API endpoint for get_connectors_in_bbox](https://github.com/catmaid/CATMAID/issues/1999) that needed to be fixed for this approach to work in general cases where a connector already exists at the desired location but is not linked to any treenode – this is a case that comes up in the next situation.

2. When using force_id=True to replace the skeleton of a neuron, if import_connectors=True is also used, then the desired behavior in my opinion would be for 1. unlink the skeleton that already existed in the target project before the upload from all its connectors, then 2. replace the old treenodes with the new treenodes and 3. upload the neuron's connectors, **avoiding creating a new connector at any location where a connector already exists** – and if the neuron was previously uploaded with its connectors, almost all of the connectors to be uploaded will in fact already exist in the target project. The current behavior is that all connectors in the neuron get uploaded as new, which creates tons of duplicates.
Proposed fix: I'm pretty sure adding the check_existing option to add_connector will basically be all that's necessary to make this occur as desired, though I feel like there will be some corner cases that will need to be carefully tested to see if any additional logic needs to be built in to handle them.

I'm happy to implement these and submit a pull request with my changes. Let me know if you think this would be useful, if you see any logic errors in my explanation, and if you can think of any corner cases I need to be careful to consider.

**Comment by schlegelp** [comment]
Hi Jasper,

Your proposed changes sounds good to me. I might suggest moving the entire connector transfer into new separate function, something like `transfer_connectivity(check_existing=True/False)`, that implements this behaviour. `transfer_neuron(connectors=True)` would then simply call that function. This way, we (a) prevent `transfer_neuron` to become too complex and (b) allow users to run them independently (e.g. to update connectivity but not the neuron) if they wish to do so.

I'd be very happy for you to have a crack at it!

**Comment by jtmaniatesselvin** [comment]
Great, we'll have a go at it. It seems to me that it might be wise to add the check_existing logic into add_connector directly, because then any pymaid function or user scripts can access this behavior if they want to. (I'm not familiar with all the places in pymaid that call add_connector, but presumably check_existing logic has the potential to be useful for more than just upload_neuron/transfer_neuron.) What do you think?

You make a good point that having a dedicated transfer_connectivity function makes sense so that users can call that directly, independently from upload_neuron/transfer_neuron. We'll try to put something like this together.

**Comment by schlegelp** [comment]
Yes, fair point re `add_connector`. 

By-the-by: I just pushed some changes for `CatmaidInstance` that make it easier/more intuitive to connect to public Catmaid Servers as per our email conversation in February (52c09d10f63f871da7782074baa4b00bf1e9449d). 

Most importantly, the arguments (order/name) have changed:
```
old: CatmaidInstance(server, authname, authpassword, authtoken, ...)
new: CatmaidInstance(server_url, token, http_user=None, http_pw=None, ...)
```
