### ISSUE TITLE
module 'pymaid' has no attribute 'Viewer'

### ISSUE THREAD

**Issue by michaelsmclayton** [schlegelp/pymaid#208]
Hi, perhaps similar to [pgibb96](https://github.com/pgibb96), but it seems the Viewer module is now missing?

**Comment by schlegelp** [comment]
Hard to debug without knowing what exactly it is you are trying to do when getting this error. In general it's a good idea to post the full error traceback and a minimal example to reproduce the error. 

That being said: `pymaid` has no `Viewer` anymore as the entire visualization (and many other functions) has been moved to `navis`. In almost all cases you will be able to simply replace `pymaid.some_function` with `navis.some_function`. So for the viewer, for example:
```Python
n = pymaid.get_neuron(16)
v = navis.Viewer()
v.add(n)
```

**Comment by michaelsmclayton** [comment]
Thank very much for this quick reply! Yes I think I have been working with an older version. It looks like I will need to update my code to this newest version.

BTW, I am a new postdoc in Marta Zlatic's lab at the LMB, and am really loving pymaid! Thank you very much for making this great software 👍

**Comment by schlegelp** [comment]
Cool. Sorry for the birthing pains with making pymaid dependent on navis but it makes my life much much easier in the long run :)

**Comment by schlegelp** [comment]
Can I close this issue @michaelsmclayton ?

**Comment by michaelsmclayton** [comment]
Sorry for my delayed reply. Yes feel free to close this issue. Thanks again for your help.
