### ISSUE TITLE
strahler order calculations consider "not a branch" tags

### ISSUE THREAD

**Issue by schlegelp** [schlegelp/pyMaid#29]
Should in these cases simply assign the successor branch's strahler order to the "not a branch" branch.

**Comment by jefferis** [comment]
Alternatively consider providing a function that prunes "not a branch" branches. Have been meaning to do this myself.

**Comment by schlegelp** [comment]
How would you deal with pre/postsynapses on these branches? Relocate to the parent branch?

**Comment by schlegelp** [comment]
Added `remove_tagged_branches` with d9e65f1989094f456b39a92c9185cc3a336e765c
