### ISSUE TITLE
feature request: make cut_neuron accept multiple cut nodes

### ISSUE THREAD

**Issue by katiestevens** [schlegelp/pyMaid#60]

**Comment by schlegelp** [comment]
First implemented with 316cf6423bab1ad183a314a21ea65f96f968ddb6

I'll leave this issue open for TO-DOs:
- Fix result's distal->proximal order. Currently the distal->proximal order is only guaranteed for single cuts. For example: if a second cut is made in the distal segment, the order of fragments will currently be: `proximal_first_cut, distal_second_cut, proximal_second_cut`

**Comment by schlegelp** [comment]
Last bugs fixed with 525fcd3d51d28239d2815529605ac8cd37aab070
